// Generates the API types from the OpenAPI contract published with an api release.
//   node scripts/contract.js sync   downloads contract.json's version and rewrites the types
//   node scripts/contract.js check  fails if the committed types differ from that version
import { readFileSync, writeFileSync } from 'node:fs';

import openapiTS, { astToString } from 'openapi-typescript';

const CONTRACT_FILE = new URL('../contract.json', import.meta.url);
const TYPES_FILE = new URL('../src/services/api/generated/api-contract.ts', import.meta.url);

const { repository, version } = JSON.parse(readFileSync(CONTRACT_FILE, 'utf8'));
const contractUrl = `https://github.com/${repository}/releases/download/${version}/openapi.json`;

const generateTypes = async () => {
  const response = await fetch(contractUrl);
  if (!response.ok) {
    throw new Error(`Could not download ${contractUrl}: HTTP ${response.status}`);
  }
  const document = await response.json();
  const header = [
    '// Generated by `npm run contract:sync` from the API contract. Do not edit by hand.',
    `// Source: ${repository}@${version} (OpenAPI ${document.info.version})`,
    '',
  ].join('\n');
  return header + astToString(await openapiTS(document));
};

const commands = {
  sync: async () => {
    writeFileSync(TYPES_FILE, await generateTypes());
    console.log(`API types generated from ${repository}@${version}`);
  },
  check: async () => {
    const committed = readFileSync(TYPES_FILE, 'utf8');
    if (committed !== (await generateTypes())) {
      throw new Error(
        `src/services/api/generated/api-contract.ts does not match ${repository}@${version}. Run npm run contract:sync.`,
      );
    }
    console.log(`API types match ${repository}@${version}`);
  },
};

const command = commands[process.argv[2]];
if (!command) {
  console.error('Usage: node scripts/contract.js <sync|check>');
  process.exit(1);
}
await command().catch((error) => {
  console.error(error.message);
  process.exitCode = 1;
});
